name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                lfs: true
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.11'

            - name: Install dependencies
              run: npm install --force

            - name: Build project
              run: |
                npm run build
                mv dist/AITesting/browser/* dist/

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.5.0
              with:
                  branch: gh-pages
                  folder: dist
